### ISSUE TITLE
Error at the end of the process

### ISSUE THREAD

**Issue by pcav** [alexisdupontroc/AreaAlongVector#5]
The process seems to run smoothly, but returns an error at the end:

Layer is not valid: The layer /home/paolo/buttalo is not a valid layer and can not be added to the map

**Comment by alexisdupontroc** [comment]
Hi, thanks form reporting this issue.
Could you explain me how to see such an error. I only get the message "pluggin ended succefully". Is there a special mode to debug and show such error messages in Qgis message window ?

**Comment by pcav** [comment]
Nothing special, just running the plugin as usual. It may be due to unfit data, but nevertheless the error should be intercepted. Could you provide sample data to check they work in my setting?

**Comment by alexisdupontroc** [comment]
Normaly you should have a sample data loaded when you click on "example" in the vector menu.

**Comment by pcav** [comment]
With sample data it works, thanks (with a warning on the first run, which I couldn't read, not saved in the log).
Thanks.
